version: '3'
services:
  api:
    build: .
    env_file:
      - .env
    command:
      - "python"
      - "main.py"
    ports:
      - "8000:8000"
    restart: always

  test_container:
    build: .
    env_file:
      - .env
    command:
      - "python"
      - "test_container.py"
    restart: always

networks:
  default: