name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Перезапуск Docker на сервере
        uses: appleboy/ssh-action@master
        run: echo "Host is ${{ secrets.SERVER_HOST }}"

        with:
        
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/vin
            docker-compose pull
            docker-compose up -d
