name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH key (только для отладки!)
        run: echo "${{ secrets.SERVER_SSH_KEY }}" | head -n 5


      - name: 🔄 Перезапуск Docker на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          fingerprint: "SHA256:jTR8qgXi7Yzh/l3JpWlSmYmMb2YXDaL2kODBQhIsMc0"
          script: |
            cd /home/vin
            docker-compose pull
            docker-compose up -d